/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "P140Gpio.h"

#include "android/log.h"
#include<sys/ioctl.h>
#include<fcntl.h>
static const char *TAG="serial_port";
#define LOGI(fmt, args...) __android_log_print(ANDROID_LOG_INFO,  TAG, fmt, ##args)
#define LOGD(fmt, args...) __android_log_print(ANDROID_LOG_DEBUG, TAG, fmt, ##args)
#define LOGE(fmt, args...) __android_log_print(ANDROID_LOG_ERROR, TAG, fmt, ##args)

#define DEVICE_NAME "/dev/imx6_gpio"

int fd;

JNIEXPORT void JNICALL Java_com_cynoware_posmate_sdk_io_P140Gpio_openDrawer
        (JNIEnv *env, jclass class){

    fd = open(DEVICE_NAME,O_RDWR);
    if (fd < 0){
        LOGE("open device imx6_gpio  failed");
    } else{
        LOGI("========================openDrawer====================");
        ioctl(fd,0x1,NULL) ;
    }
}

JNIEXPORT void JNICALL Java_com_cynoware_posmate_sdk_io_P140Gpio_closeDrawer
        (JNIEnv *env, jobject object){
    LOGI("========================closeDrawer====================");
    ioctl(fd,0x0,NULL) ;
    close(fd);
}
