/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cynoware_posmate_sdk_io_P140Gpio */

#ifndef _Included_com_cynoware_posmate_sdk_io_P140Gpio
#define _Included_com_cynoware_posmate_sdk_io_P140Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cynoware_posmate_sdk_io_P140Gpio
 * Method:    openDrawer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cynoware_posmate_sdk_io_P140Gpio_openDrawer
  (JNIEnv *, jobject);

/*
 * Class:     com_cynoware_posmate_sdk_io_P140Gpio
 * Method:    closeDrawer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cynoware_posmate_sdk_io_P140Gpio_closeDrawer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
